version: '2'
services:

  thesis-nginx:
    image: nginx:1.12.2-alpine
    container_name: thesis-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - <CURR_DIR>/nginx/nginx.conf:/etc/nginx/nginx.conf
      - <CURR_DIR>/nginx/server.key:/etc/nginx/certs.d/server.key
      - <CURR_DIR>/nginx/server.crt:/etc/nginx/certs.d/server.crt
      - <CURR_DIR>/nginx/usr/share/nginx/html/:/usr/share/nginx/html/
    restart: always
    depends_on:
      - thesis-core

  thesis-core:
    image: nik90/thesis-core:<REVISION>
    container_name: thesis-core
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${THESIS_DB_HOST}:${THESIS_DB_PORT}/thesis_core
      - SPRING_DATASOURCE_USERNAME=${THESIS_DB_CORE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=ENC(${THESIS_DB_CORE_PASSWORD})
      - SPRING_JPA_SHOW_SQL=false
      - PRIVATEKEY_FILENAME=/opt/cfg/rsa/private_key.der
      - PUBLICKEY_FILENAME=/opt/cfg/rsa/public_key.der
      - THESIS_TIMEZONE=${THESIS_TIMEZONE}
      - EXAMPLE_STYLE_ENABLE=true
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

    volumes:
      - ${HOST_THESIS_CORE_SARBOX_DIR}:/var/thesis/sarbox/thesis-core/
      - <CURR_DIR>/var/thesis/sarbox/dictionaries:/var/thesis/sarbox/dictionaries
    restart: always

  thesis-ui:
    image: nik90/thesis-ui:<REVISION>
    container_name: thesis-ui
    ports:
      - "80"
    restart: always

networks:
  default:
    external:
      name: thesis
